config/routes.rb
Rails.application.routes.draw do
  resources :supports
  resources :infos
  resources :asks
  resources :communities
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "home#index"
  
  post '/communities/:id/like', to: 'likes#like_toggle', as: 'like_community'
  
  post '/asks/:ask_id' =>"askcomments#create"
  
  get 'comm_comment/create'
  get 'comm_comment/destroy'
  
  post 'communities/new' => "community#new"
  post 'communities/comment' => "comm_comment#create"
  delete '/communities/:article_id/comment/:id' =>"comm_comment#delete"

end

app/models/ask.rb
class Ask < ActiveRecord::Base
    searchable do
    text :title
    text :content 
  end
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  before_action :set_ask, only: [:show, :edit, :update, :destroy]

  # GET /asks
  # GET /asks.json
  def index
    @search = Ask.search do
        fulltext params[:search]
    end
     @asks = @search.results
 
    
    @asks = Ask.all.reverse
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
    
  end

  # GET /asks/1
  # GET /asks/1.json
  def show
  end

  # GET /asks/new
  def new
    @ask = Ask.new
  end

  # GET /asks/1/edit
  def edit
  end

  # POST /asks
  # POST /asks.json
  def create
    @ask = Ask.new(ask_params)

    respond_to do |format|
      if @ask.save
        format.html { redirect_to @ask, notice: 'Ask was successfully created.' }
        format.json { render :show, status: :created, location: @ask }
      else
        format.html { render :new }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asks/1
  # PATCH/PUT /asks/1.json
  def update
    respond_to do |format|
      if @ask.update(ask_params)
        format.html { redirect_to @ask, notice: 'Ask was successfully updated.' }
        format.json { render :show, status: :ok, location: @ask }
      else
        format.html { render :edit }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asks/1
  # DELETE /asks/1.json
  def destroy
    @ask.destroy
    respond_to do |format|
      format.html { redirect_to asks_url, notice: 'Ask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ask
      @ask = Ask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ask_params
      params.require(:ask).permit(:title, :content)
    end
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/views/asks/_form.html.erb
<%= form_for(@ask) do |f| %>
  <% if @ask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ask.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @ask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
<table class="table table-bordered">
    <tbody>
        <form action="write_ok.jsp" method="post" encType="multiplart/form-data">
            <tr>
                <th>제목: </th>
                <td><%= f.text_field :title, id: :info_title %></td>
            </tr>
            <tr>
                <th>내용: </th>
                <td><%= f.text_area :content, id: :info_content %></td>
            </tr>
            <tr>
                <th>첨부파일: </th>
                <td><input type="text" placeholder="파일을 선택하세요. " name="filename" class="form-control"/></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <%= f.submit %>
                    
                    <!-- <a class="btn btn-default" onclick="sendData()"> 등록 </a>
                    <a class="btn btn-default" type="reset"> reset </a>
                    <a class="btn btn-default" onclick="javascript:location.href='list.jsp'">글 목록으로...</a> -->
                </td>
            </tr>
        </form>
    </tbody>
</table>
</div>

  <div class="actions">
    
  </div>
<% end %>

app/views/asks/edit.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>쉽고 빠르게 대타찾는, 대타몬!</title>
 
</head>
  <br>
  <br><br><br><br>



<div align ="center">
    <h1> 문의사항 글수정</h1>
</div>


<center><%= render 'form' %>
<%= link_to 'Show', @ask %> 

<center><%= link_to 'Back', asks_path %>

app/views/asks/index.html.erb
 <html lang="en">
 <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <title>쉽고 빠르게 대타찾는, 대타몬!</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/freelancer.min.css" rel="stylesheet">
    <%= render 'layouts/header'%>
</head>
<body>
  <p id="notice"><%= notice %></p>

  <div align = "right">
    <% if user_signed_in? %>
         <%= current_user.email %><br>
        <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "로그인", user_session_path %>
        <%= link_to "회원가입", "/users/sign_up" %>
    <% end %>
  </div>
  
  <section class="banner-area" id="home">
  		<div class="container">
  			<div class="row d-flex align-items-center justify-content-center">
  				<div class="banner-content col-lg-3 col-md-3">
  					<center><h1 class="title">문의사항</h1>
  				</div>
  			</div>
  		</div>
    </section>
  

<style>
  .container {
      font-size:15px;
  }
</style>

<center>

<br>
<div class="container" >


<div align="right">
  <%= link_to '새 글 쓰기', new_ask_path %>
</div>
<br>
<table class="table table-hover">

    <tr align="left" style = "background-color:rgb(30,177,138)">
      
      <th><font color="white">제목</font></th>
      <th><font color="white">작성자</font></th>
      <th><font color="white">등록일</font></th>
      
    </tr>

  <tbody>
    
    <% @asks.each do |ask| %>
      <tr height="30" align="left">
       
        <td width="50%" align="left"><i class="fa fa-user-o" aria-hidden="true"></i> <%= link_to ask.title, ask %></td>
        <% str = ask.created_at %>
        <td width="20%"><%= current_user.email %></td>
        <td width="20%" align="left"><i class="fa fa-clock-o" aria-hidden="true"><%= "#{time_ago_in_words(ask.created_at)} 전" %></td>
        
      </tr>
     
    <% end %>
  </tbody>
  
</table>

<br>
<div align="right">
<%= form_tag asks_path, :method => :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "검색", :name => nil %>
<% end %>
</div>





<br><br>
</body>

app/views/asks/new.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>쉽고 빠르게 대타찾는, 대타몬!</title>
 
</head>
  <br>
  <br><br><br><br>



<div align ="center">
    <h1> 문의사항 글작성</h1>
</div>


<center><%= render 'form' %>
<br><br>
<center><%= link_to 'Back', asks_path %>

app/views/asks/show.html.erb
<html>
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <title>쉽고 빠르게 대타찾는, 대타몬!</title>

    
  </head>
  <body>
    <div class="container">
      <div class="layer">
        <div class="article">
          <br>
          <div align="left"><h3><%= @ask.title %></h3></div>
          <div align ="left">
            <h6>작성자:  <%= current_user.email %></h6>
          </div>
          
          
          
          <hr>
          <h6 align="right"><%= Time.now %></h6>
          <div style="padding:300" class="article-content" >
            <center><%= @ask.content %>
          </div>
          <br><br>
          <div class="button" align = "left">
            <%= link_to '목록', asks_path %>
            <%= link_to '수정', edit_ask_path(@ask) %>
            <%= link_to '삭제', @ask, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          <hr>
          
        </div>
      </div>
      
      		
      	
    </div>
    


  </body>
</html>