config/routes.rb
Rails.application.routes.draw do
  resources :supports
  resources :infos
  resources :asks
  resources :communities
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "home#index"
  
  post '/communities/:id/like', to: 'likes#like_toggle', as: 'like_community'
  
  post '/asks/:ask_id' =>"askcomments#create"
  
  get 'comm_comment/create'
  get 'comm_comment/destroy'
  
  post 'communities/new' => "community#new"
  post 'communities/comment' => "comm_comment#create"
  delete '/communities/:article_id/comment/:id' =>"comm_comment#delete"

end

app/models/community.rb
class Community < ActiveRecord::Base
  mount_uploader :image
  
    searchable do
    text :title
    text :content
  end
   has_many :comments
   is_impressionable
   
  
   has_many :likes
    has_many :l_users, through: :likes, source: :user
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    
    @search = Community.search do
        fulltext params[:search]
    end
    @communities = @search.results
    
  
    @communities = Community.all.reverse
    
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
  
  end
  impressionist actions: [:show], unique: [:ip_address]
  # GET /communities/1
  # GET /communities/1.json
  def show
    @comm_comments = CommComment.all
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:title, :content, :image)
    end
    
    def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    #좋아요가 눌렸는지 체크
    if like.nil?
      Like.create(user_id: current_user.id, post_id: params[:post_id])
    else
      like.destroy
    end
    redirect_to :back
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for(@community) do |f| %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
<table class="table table-bordered">
    <tbody>
        
        <form action="write_ok.jsp" method="post" encType="multiplart/form-data">
            
            
            <tr>
                <th>제목: </th>
                <td><%= f.text_field :title, id: :info_title %></td>
            </tr>
            <tr>
                <th>내용: </th>
                <%= tinymce :language => "en" %>
                <td><%= f.text_area :content, id: :community_content, class: "form-control tinymce", rows: "10" %></td>
            </tr>
            
           
            <tr>
                <th>첨부파일: </th>
                <td><%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <%= f.submit %>
                    
                    <!-- <a class="btn btn-default" onclick="sendData()"> 등록 </a>
                    <a class="btn btn-default" type="reset"> reset </a>
                    <a class="btn btn-default" onclick="javascript:location.href='list.jsp'">글 목록으로...</a> -->
                </td>
            </tr>
        </form>
    </tbody>
</table>
</div>

  <div class="actions">
    
  </div>
<% end %>

app/views/communities/edit.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>쉽고 빠르게 대타찾는, 대타몬!</title>
 
</head>
  <br>
  <br><br><br><br>



<div align ="center">
    <h1> 대타톡 글수정</h1>
</div>


<center><%= render 'form' %>
<%= link_to 'Show', @community %> 

<center><%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
 <html lang="en">
 <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <title>쉽고 빠르게 대타찾는, 대타몬!</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/freelancer.min.css" rel="stylesheet">
    <%= render 'layouts/header'%>
</head>
<body>
  <p id="notice"><%= notice %></p>

  <div align = "right">
    <% if user_signed_in? %>
         <%= current_user.email %><br>
        <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "로그인", user_session_path %>
        <%= link_to "회원가입", "/users/sign_up" %>
    <% end %>
  </div>
  
  <section class="banner-area" id="home">
  		<div class="container">
  			<div class="row d-flex align-items-center justify-content-center">
  				<div class="banner-content col-lg-3 col-md-3">
  					<center><h1 class="title">대타톡</h1>
  				</div>
  			</div>
  		</div>
    </section>
  

<style>
  .container {
      font-size:15px;
  }
</style>

<center>

<br>
<div class="container" >




<table class="table table-hover">

    <tr align="left" style = "background-color:rgb(30,177,138)">
      <th><font color="white">No</font></th>
      <th><font color="white">제목</font></th>
      <th><font color="white">등록일</font></th>
      <th align="center"><font color="white">조회수</font></th>
      <th><font color="white">추천</font></th>
    </tr>

  <tbody>
    
    <% @communities.each do |community| %>
      <tr height="30" align="center">
        <td width="10%" align="left"><i class="fa fa-user-o" aria-hidden="true"></i> <%= community.id %></td>
        <td width="50%" align="left"><i class="fa fa-user-o" aria-hidden="true"></i> <%= link_to community.title, community %></td>
        <% str = community.created_at %>
        
        <td width="20%" align="left"><i class="fa fa-clock-o" aria-hidden="true"><%= "#{time_ago_in_words(community.created_at)} 전" %></td>
        <td width="10%" align="left"><%= community.impressionist_count %></td>
        <td width="10%" align="left"><i class="far fa-thumbs-up"></i></i> <%= community.likes.size %></td>
      </tr>
     <br>
     
    <% end %>
  </tbody>
  
</table>
<div align="right">
  <%= link_to '새 글 쓰기', new_community_path %>
</div>
<br>
<div align="right">
<%= form_tag communities_path, :method => :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "검색", :name => nil %>
<% end %>
</div>





<br><br>
</body>

app/views/communities/new.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>쉽고 빠르게 대타찾는, 대타몬!</title>
 
</head>
  <br>
  <br><br><br><br>



<div align ="center">
    <h1> 대타톡 글작성</h1>
</div>


<center><%= render 'form' %>
<br><br>
<center><%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<html>
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <title>쉽고 빠르게 대타찾는, 대타몬!</title>

    
  </head>
  <body>
    <div class="container">
      <div class="layer">
        <div class="article">
          <br>
          <div align="left"><h3><%= @community.title %></h3></div>
          <div align ="left">

          </div>
          
          
          
          <hr>
          <h6 align="right"><%= Time.now %></h6>
          <div style="padding:300" class="article-content" >
            <center>
            <%= image_tag("#{@community.image}") %>
            <%= @community.content.html_safe %></center>
          </div>
          <br><br>
          <div class="button" align = "left">
            <%= link_to '목록', communities_path %>
            <%= link_to '수정', edit_community_path(@community) %>
            <%= link_to '삭제', @community, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          
          <div class="like" align="right">
            <% if @community.l_users.include?(current_user) %>
              <!--좋아요를 했다면-->
              <span class="like_after">
                <i class="far fa-thumbs-up"> </i><%= link_to '추천!', like_community_path, method: :post %>
              </span>
              <% else %>
              <!--좋아요를 안했다면-->
              <span class="like_before">
               <i class="far fa-thumbs-up"> </i><%= link_to '추천', like_community_path, method: :post %>
              </span>
            <% end %>
            
            <a> <%= @community.likes.count %></a>
       </div>
          <hr>
          
        </div>
      </div>
       
      		
      	
    </div>
    <center><h4>댓글쓰기</h4></center>
    <div align="center" class="comment-input">
            <%=form_tag '/communities/comment', method: 'post' do %>
              <input type="hidden" name="user" value="<%=current_user.name%>">
            	<input type="hidden" name="id" value="<%=@community.id%>">
            	<input style="text-align:center; width:1200px; height:200px; letter-spacing: -5px" type="text" name="comment"><br><br>
            	<right><input align="right" type="submit" ></right>
            <% end %>
    </div>
 
    
    <div align="center">
    <h3>댓글</h3>
    <%@comm_comments.each do |comment| %> 
      	<% if comment.article_id == @community.id %>
      		<div class="comments">
      		  <p class="user-name">
      		    <% if comment.user == current_user.name %>
      		    <%=comment.user%>
      		     <a class="button-delete"  href="/communities/<%=@community.id%>/comment/<%=comment.id%>" data-method="delete" class="btn btn-default">delete</a>
      		    <% end %>
      		  </p>
      		  <!--%= link_to '삭제', [comment.] , method: :delete, data: { confirm: 'Are you sure?' } %-->
      		  <hr class="split">
      			<left><p class=""><%=comment.message%></p></left>
      			<br><br>
      		</div>
      	<% end %>
      <% end %>
    </div>
    
    
    

  </body>
</html>